//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EternalPlay.ReusableCore.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EternalPlay.ReusableCore.Web.ControlResources", typeof(ControlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting.
        /// </summary>
        internal static string Button_Submit_PostText {
            get {
                return ResourceManager.GetString("Button_Submit_PostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Button_Submit_Text {
            get {
                return ResourceManager.GetString("Button_Submit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Entry_Day_UserFriendlyName {
            get {
                return ResourceManager.GetString("Entry_Day_UserFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string Entry_Hour_UserFriendlyName {
            get {
                return ResourceManager.GetString("Entry_Hour_UserFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string Entry_Minute_UserFriendlyName {
            get {
                return ResourceManager.GetString("Entry_Minute_UserFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Entry_Month_UserFriendlyName {
            get {
                return ResourceManager.GetString("Entry_Month_UserFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  was entered inappropriately.
        /// </summary>
        internal static string Entry_Pattern_ErrorMessage {
            get {
                return ResourceManager.GetString("Entry_Pattern_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  should be expressed as an integer.
        /// </summary>
        internal static string Entry_Pattern_Integer_ErrorMessage {
            get {
                return ResourceManager.GetString("Entry_Pattern_Integer_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[0-9\\-]*$.
        /// </summary>
        internal static string Entry_Pattern_Integer_Expression {
            get {
                return ResourceManager.GetString("Entry_Pattern_Integer_Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  should be expressed as a positive integer.
        /// </summary>
        internal static string Entry_Pattern_IntegerPositive_ErrorMessage {
            get {
                return ResourceManager.GetString("Entry_Pattern_IntegerPositive_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[0-9]*$.
        /// </summary>
        internal static string Entry_Pattern_IntegerPositive_Expression {
            get {
                return ResourceManager.GetString("Entry_Pattern_IntegerPositive_Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string Entry_Pattern_Text {
            get {
                return ResourceManager.GetString("Entry_Pattern_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter four digit Year values, like 1971 or 2001..
        /// </summary>
        internal static string Entry_Pattern_Year_ErrorMessage {
            get {
                return ResourceManager.GetString("Entry_Pattern_Year_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  value must be between a minimum of .
        /// </summary>
        internal static string Entry_Range_ErrorMessage1 {
            get {
                return ResourceManager.GetString("Entry_Range_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and a maximum of .
        /// </summary>
        internal static string Entry_Range_ErrorMessage2 {
            get {
                return ResourceManager.GetString("Entry_Range_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&lt;.
        /// </summary>
        internal static string Entry_Range_Text {
            get {
                return ResourceManager.GetString("Entry_Range_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is a required value.
        /// </summary>
        internal static string Entry_Required_ErrorMessage {
            get {
                return ResourceManager.GetString("Entry_Required_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string Entry_Required_Text {
            get {
                return ResourceManager.GetString("Entry_Required_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string Entry_Second_UserFriendlyName {
            get {
                return ResourceManager.GetString("Entry_Second_UserFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Entry_Year_UserFriendlyName {
            get {
                return ResourceManager.GetString("Entry_Year_UserFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0-9\\-].
        /// </summary>
        internal static string Invariant_KeystrokeFilterExpression_NegativePositiveInteger {
            get {
                return ResourceManager.GetString("Invariant_KeystrokeFilterExpression_NegativePositiveInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0-9].
        /// </summary>
        internal static string Invariant_KeystrokeFilterExpression_PositiveInteger {
            get {
                return ResourceManager.GetString("Invariant_KeystrokeFilterExpression_PositiveInteger", resourceCulture);
            }
        }
    }
}
