//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EternalPlay.ReusableCore.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebExceptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EternalPlay.ReusableCore.Web.WebExceptionResources", typeof(WebExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The associated label was not found within the same naming container as the entry control.
        /// </summary>
        internal static string Entry_AssociatedLabelNotFound_MessageText {
            get {
                return ResourceManager.GetString("Entry_AssociatedLabelNotFound_MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeystrokeFilterExpression is required if keystroke filtering is turned on.
        /// </summary>
        internal static string Entry_KeystrokeFilterExpression_MessageText {
            get {
                return ResourceManager.GetString("Entry_KeystrokeFilterExpression_MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorTextPlacement of AdjacentToLabel requires the AssociatedLabelId value be provided.
        /// </summary>
        internal static string Entry_LabelRequiredForPlacement_MessageText {
            get {
                return ResourceManager.GetString("Entry_LabelRequiredForPlacement_MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinimumValue and MaximumValue are required to both be present or absent.
        /// </summary>
        internal static string Entry_MinAndMaxValues_MessageText {
            get {
                return ResourceManager.GetString("Entry_MinAndMaxValues_MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserFriendlyName is required if the control is editable.
        /// </summary>
        internal static string Entry_UserFriendlyName_MessageText {
            get {
                return ResourceManager.GetString("Entry_UserFriendlyName_MessageText", resourceCulture);
            }
        }
    }
}
